sonar.projectKey=reservas-psicologo
sonar.projectName=Sistema de Reservas - Psicologo
sonar.sources=src
sonar.tests=src/test
sonar.test.inclusions=src/test/**/*.test.tsx,src/test/**/*.test.ts
sonar.exclusions=node_modules/**,dist/**,coverage/**,**/*.config.*
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8